CREATE TABLE device_keys (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    -- A unique identifier for the device, generated by the client
    device_identifier TEXT NOT NULL,
    -- The Curve25519 public key for the device (raw bytes)
    public_key BYTEA NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    last_seen_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    -- Ensures that each device identifier is unique per user
    UNIQUE (user_id, device_identifier)
);

CREATE INDEX idx_device_keys_user_id ON device_keys(user_id);
CREATE INDEX idx_device_keys_user_id_device_identifier ON device_keys(user_id, device_identifier);

COMMENT ON COLUMN device_keys.device_identifier IS 'Client-generated unique identifier for the device';
COMMENT ON COLUMN device_keys.public_key IS 'Curve25519 public key bytes for E2EE';
