// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Group struct {
	ID        int32
	Name      string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type Message struct {
	ID        int32
	Content   string
	UserID    pgtype.Int4
	GroupID   pgtype.Int4
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type User struct {
	ID        int32
	Username  string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type UserGroup struct {
	ID        int32
	UserID    pgtype.Int4
	GroupID   pgtype.Int4
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	Admin     bool
}
