// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type DeviceKey struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
	// Client-generated unique identifier for the device
	DeviceIdentifier string `json:"device_identifier"`
	// Curve25519 public key bytes for E2EE
	PublicKey  []byte           `json:"public_key"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	LastSeenAt pgtype.Timestamp `json:"last_seen_at"`
}

type Group struct {
	ID          uuid.UUID        `json:"id"`
	Name        string           `json:"name"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
	StartTime   pgtype.Timestamp `json:"start_time"`
	EndTime     pgtype.Timestamp `json:"end_time"`
	Description pgtype.Text      `json:"description"`
	Location    pgtype.Text      `json:"location"`
	ImageUrl    pgtype.Text      `json:"image_url"`
}

type Message struct {
	ID        uuid.UUID        `json:"id"`
	UserID    *uuid.UUID       `json:"user_id"`
	GroupID   *uuid.UUID       `json:"group_id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
	// Encrypted message content (libsodium secretbox output)
	Ciphertext []byte `json:"ciphertext"`
	// Nonce used for symmetric encryption of the ciphertext
	MsgNonce []byte `json:"msg_nonce"`
	// JSON array of per-recipient sealed symmetric keys. Each element: {deviceId, ephPubKey, keyNonce, sealedKey}
	KeyEnvelopes []byte `json:"key_envelopes"`
}

type User struct {
	ID        uuid.UUID        `json:"id"`
	Username  string           `json:"username"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
	Email     string           `json:"email"`
	Password  pgtype.Text      `json:"password"`
}

type UserGroup struct {
	ID        uuid.UUID        `json:"id"`
	UserID    *uuid.UUID       `json:"user_id"`
	GroupID   *uuid.UUID       `json:"group_id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
	Admin     bool             `json:"admin"`
}
